---
title: "parameterized_reports"
author: "LO"
params:
  date: !r Sys.Date()
output: html_documenthttps://bookdown.org/yihui/rmarkdown-cookbook/parameterized-reports.html
---


```{r}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(countrycode))
```

```{r}
countries <- readRDS("countries_map.rds")
```

```{r}
class(countries)
```

```{r}
profile = countries %>% as.data.frame() %>% 
  filter(ADMIN=="Ukraine") %>%
  select(ADMIN) %>%
  mutate(code=countrycode(ADMIN, origin = 'country.name', destination='iso2c'),
         file="pdf/wipo_Ukraine.pdf",
         GII_2020_rank=45,
         "Output Rank"= 37,
         "Input Rank" = 71,
         Income="Lower middle",
         Region="EUR",
         "Population(mn)" = 44.0,
         "GDP, PPP$"=409.3,
         "GDP per capita, PPP$"=8533.5,
         "GII 2019 rank"=47
         )
```

```{r}
df1 = tribble(
~"ADMIN",~"GII 2020 rank",~"Output rank",~"Input rank",~Income,~Region,~"Population (mn)",~"GDP PPP$",~"GDP per capita PPP$",~"GII 2019 rank",
"Ukraine",47,37,71,"Lower middle","EUR",44.0,409.3,8533.5,47,
"United Kingdom",4,3,6,"High","EUR",67.5,3131.2,40881.3,5
)
```

```{r}
agg= countries
agg$data = left_join(agg@data, df1, by="ADMIN")
```

```{r}
agg$rank = ifelse(agg$ADMIN=="Ukraine",47,NA)
agg$rank = ifelse(agg$ADMIN=="United Kingdom",4,agg$rank)
```


```{r}
m = leaflet(agg) %>%
  setView(14.415556, 50.094722, 4)
```


```{r}
df1 = tribble(
~"Country",~"GII 2020 rank",~"Output rank",~"Input rank",~Income,~Region,~"Population (mn)",~"GDP PPP$",~"GDP per capita PPP$",~"GII 2019 rank",
"Ukraine",47,37,71,"Lower middle","EUR",44.0,409.3,8533.5,47,
"United Kingdom",4,3,6,"High","EUR",67.5,3131.2,40881.3,5
)
```

```{r}
df1 %>% filter(Country=="United Kingdom")
```

```{r}
df2 = tribble(
  ~"Country",~"Group",~"Score",~"Rank",
  "Ukraine","INSTITUTIONS",55.6,93,
  "Ukraine","HUMAN CAPITAL & RESEARCH",40.5,39,
  "Ukraine","INFRASTRUCTURE",33.1,94,
  "Ukraine","MARKET SOPHISTICATION",42.1,99,
  "Ukraine","BUSINESS SOPHISTICATION",29.5,54,
  "Ukraine","KNOWLEDGE & TECHNOLOGY OUTPUTS",35.1,25,
  "Ukraine","CREATIVE OUTPUTS",29.9,44,
  "United Kingdom","INSTITUTIONS",86.1,16,
  "United Kingdom","HUMAN CAPITAL & RESEARCH",58.0,10,
  "United Kingdom","INFRASTRUCTURE",60.3,6,
  "United Kingdom","MARKET SOPHISTICATION",74.4,5,
  "United Kingdom","BUSINESS SOPHISTICATION",51.0,19,
  "United Kingdom","KNOWLEDGE & TECHNOLOGY OUTPUTS",54.4,9,
  "United Kingdom","CREATIVE OUTPUTS",52.7,5
  
) %>% mutate(Group=str_to_title(Group),
               Group=fct_rev(fct_inorder(Group))) 

df2 %>% filter(Country=="United Kingdom")
```


```{r}
library(RColorBrewer)
pal <- colorNumeric("Blues", NULL, reverse = TRUE)
m %>% addPolygons(
  fillColor = ~pal(agg@data$rank),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlightOptions = highlightOptions(
    weight = 5,
    color = "orange",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label=paste(agg$ADMIN))
```




