---
title: "20231122"
date:"2023-11-22"
format: html
editor: visual
---

Food access data (2019) from [USDA](https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/) by way of [Data Is Plural 2023.11.22 edition](https://www.data-is-plural.com/archive/2023-11-22-edition/).

```{r load libraries}
library(tidyverse)
library(readxl)
library(ggtext)
library(showtext)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r load fonts}
font_add_google("Barlow")
```

```{r read in data}
des = read_xlsx("data/FoodAccessResearchAtlasData2019.xlsx", sheet=2)
df1 = read_xlsx("data/FoodAccessResearchAtlasData2019.xlsx", sheet=3)
caption="Source: USDA by way of Data Is Plural"
```

### Low income and low access tracts 0.5, 1, 10, and 20 miles, New Mexico
```{r wrangle}
df2 = df1 |> filter(State=="New Mexico") |>
  select(GEOID=CensusTract, LILATracts_1And10:LILATracts_Vehicle) |>
  pivot_longer(!GEOID) |>
  mutate(longname=case_when(name=="LILATracts_halfAnd10"~"1/2 mile for urban areas and\n10 miles for rural areas",
                            name=="LILATracts_1And10"~"1 mile for urban areas and\n10 miles for rural areas",
                            name=="LILATracts_1And20"~"1 mile for urban areas and\n20 miles for rural areas",
                            name=="LILATracts_Vehicle"~"Using vehicle access or\nmeasured at 20 miles",),
         name=factor(name, ordered = TRUE, levels=c("LILATracts_halfAnd10","LILATracts_1And10","LILATracts_1And20","LILATracts_Vehicle"))) |>
  arrange(name) |>
  mutate(longname=fct_inorder(longname, ordered = TRUE)) |>
  filter(value==1) 

tr = tigris::tracts(state="NM",cb=TRUE,year=2019)
tr2 = tr |> right_join(df2, by="GEOID")
```

```{r plot, fig.height=1.8, fig.width=4}
tr2 |>
  ggplot() +
  geom_sf(data=tr, linewidth=.1, fill="grey98") +
  geom_sf(aes(fill=name), linewidth=.1,show.legend=FALSE) +
  MetBrewer::scale_fill_met_d("Egypt") +
  coord_sf(expand=FALSE) +
  facet_wrap(~longname, ncol=4) +
  cowplot::theme_map(10) +
  theme(text=element_text(family = "Barlow"),
        strip.text = element_text(size=9, hjust=0, vjust=.5, lineheight = 1, margin=margin(b=10)),
        panel.spacing = unit(1.2,"lines"),
        plot.title=element_text(size=13),
        plot.subtitle = element_text(size=9, margin=margin(b=10)),
        plot.caption = element_text(hjust=0, size=8, color="grey40", margin=margin(t=15)),
        ) +
  labs(title="Food Access, New Mexico, 2019",
       subtitle="Low income and low access tracts, measured at 0.5, 1, 10, and 20 miles of the nearest supermarket, supercenter, or large grocery store.",
       caption=caption)

#ggsave("export/20231122_p1.png", height=3.6, width=8, bg="#fafafa")
```

### Low access, share of population at 0.5 and 1 mile, Harris County TX

```{r wrangle}
des2 = des |>
  filter(str_detect(LongName,"Low access, population"),
         str_detect(LongName,"share")) |>
  rename(name=Field, longname=LongName)

df3 = df1 |> select(CensusTract:County, lapophalfshare,lapop1share) |>
  filter(State=="Texas", County=="Harris County") |>
  pivot_longer(lapophalfshare:lapop1share) |>
  left_join(des2, by="name") |>
  mutate(value=parse_number(value)) |>
  rename(GEOID=CensusTract) 

tr3 = tigris::tracts(state="Texas",county="Harris County",cb=TRUE,year=2019)
tr4 = tr3 |> left_join(df3, by="GEOID")
```

```{r}
theme1= cowplot::theme_map(12) +
  theme(text=element_text(family="Barlow"),
        legend.title=element_blank(),
        legend.position = "top",
        legend.box.margin = margin(l=5),
        strip.text = element_text(size=11.5,margin=margin(b=10)),
        plot.subtitle = element_text(margin=margin(b=8)),
        plot.caption = element_text(hjust=0, size=9, color="grey40", margin=margin(t=15)),
        )
```

```{r plot, fig.height=2.4, fig.width=4}
ggplot() +
  geom_sf(data=tr4, aes(fill=value), linewidth=.05, color="black") +
  coord_sf(expand=FALSE) +
  scico::scale_fill_scico(palette="nuuk", direction=-1, na.value="transparent", labels=scales::percent_format(scale=1), guide=guide_colorbar(barheight=unit(.5,"lines"),barwidth = unit(10,"lines"))) +
  facet_wrap(~fct_rev(longname)) +
  theme1 +
  labs(title="Food Access, Harris County, TX (2019)",
       subtitle="Share of population with low access by tract, measured at 1/2 mile and 1 mile of the nearest supermarket, supercenter, or\nlarge grocery store",
       caption=caption)

#ggsave("export/20231122_p2.png", height=4.8, width=8, bg="#fafafa")
```

### Low access, share of senior population, Dallas County TX

```{r}
des3 = des |> filter(str_detect(LongName,"senior"),
              str_detect(LongName,"share"),) |>
  rename(name=Field, longname=LongName)

df4 = df1 |> select(CensusTract:County, laseniorshalfshare,laseniors1share) |>
  filter(State=="Texas", County=="Dallas County") |>
  pivot_longer(!CensusTract:County) |>
  left_join(des3, by="name") |>
  mutate(value=parse_number(value)) |>
  rename(GEOID=CensusTract) 

tr5 = tigris::tracts(state="TX",county="Dallas County",cb=TRUE,year=2019)
tr6 = tr5 |> left_join(df4, by="GEOID") |> drop_na(longname)
```


```{r, fig.height=3, fig.width=4}
tr6 |>
  ggplot() +
  geom_sf(data=tr5,linewidth=.07, color="black") +
  geom_sf(aes(fill=value),linewidth=.07, color="black") +
  coord_sf(expand=FALSE) +
  scico::scale_fill_scico(palette="bamako",direction=-1, na.value="transparent",labels=scales::percent_format(scale=1), guide=guide_colorbar(barheight=unit(.5,"lines"),barwidth = unit(10,"lines"))) +
  facet_wrap(~longname) +
  theme1 +
  labs(caption=caption,
       subtitle="Share of senior population with low access by tract, measured at 1/2 mile and 1 mile of the nearest supermarket, supercenter,\nor large grocery store ",
       title="Senior residents' food access, Dallas County, TX (2019)")

#ggsave("export/20231122_p3.png", height=6, width=8, bg="#fafafa"
```

