---
title: "Line Chart Function"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(ggtext)

library(showtext)
font_add_google("Lato")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
f1= "Lato"
```

```{r}
data = read_csv("sites/classic.com-organic-traffic-all-27-Dec-2021_18-21-47.csv",show_col_types = FALSE)
subtitle ="classic.com"
source = "Data source: text"
```

```{r}
trend = function(data, source, subtitle) {
  trend = ggplot(data, aes(x=Date, y=`Organic traffic`)) +
  geom_line(color="#2663FF", size=.85) +
  geom_area(fill="#2663FF", alpha=.1) +
  geom_segment(data= data %>% filter(`Organic traffic`==max(`Organic traffic`)),
               aes(xend=Date - (as.double(Date- min(data$Date))/3),yend=`Organic traffic`)) +
  geom_richtext(data = data %>% filter(`Organic traffic`==max(`Organic traffic`)),
               aes(x= Date - (as.double(Date- min(data$Date))/3), label=glue::glue("Max Organic Traffic:<br><span style='color:#2663FF;'>**{scales::comma(`Organic traffic`)}**</span> on<br>{Date}")),
               size=3.2, family=f1, fill="#eaf0ff") +
  scale_y_continuous(labels = scales::label_number(scale= 1e-3, suffix="k"), limits=c(0,NA), expand = expansion(mult = c(0, .2))) +
  coord_cartesian(clip="off") +
  cowplot::theme_minimal_grid(10.5, line_size = .3) +
  theme(text=element_text(family=f1),
        panel.grid=element_line(linetype = "dashed"),
        plot.title.position = "plot",
        plot.title=element_text(hjust=.5, color="#2663FF"),
        plot.subtitle = element_text(hjust=.5, face="italic"),
        plot.caption.position = "plot",
        plot.caption=element_text(hjust=0, face="italic"),
        axis.line = element_line(),
        plot.margin=margin(rep(.5,4), unit="cm")) +
  labs(title="Organic Traffic", 
       subtitle=subtitle, 
       caption =source)
  return(ggsave(glue::glue("{subtitle}_organic_traffic.png"), bg="#fafafa", height=5, width=6.5))
}

trend(data, source, subtitle)
```

```{r}
data = read_csv("sites/creditninja.com-organic-traffic-all-27-Dec-2021_18-21-18.csv",show_col_types = FALSE)
subtitle ="creditninja.com"
source = "Data source: text"
```

```{r}
data = read_csv("sites/petkeen.com-organic-traffic-all-27-Dec-2021_18-14-03.csv",show_col_types = FALSE)
subtitle ="petkeen.com"
source = "Data source: text"
```

```{r}
data = read_csv("sites/busytourist.com-organic-traffic-all-27-Dec-2021_18-00-53.csv",show_col_types = FALSE)
subtitle ="busytourist.com"
source = "Data source: text"
```

```{r}
data = read_csv("sites/tinyrituals.co-organic-traffic-all-27-Dec-2021_17-59-03.csv",show_col_types = FALSE)
subtitle ="tinyrituals.co"
source = "Data source: text"
```





