---
title: "Report draft v1"
output: html_notebook
---

#Economy Profile
#United Kingdom

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggtext))
suppressPackageStartupMessages(library(showtext))
suppressPackageStartupMessages(library(gt))
suppressPackageStartupMessages(library(gtExtras))
```

```{r}
country="United Kingdom"
```

```{r}
font_add_google("Roboto")
font_add_google("Libre Franklin")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r}
df1 = tribble(
~"ADMIN",~"GII 2021 rank",~"Output rank",~"Input rank",~Income,~Region,~"Population (mn)",~"GDP PPP$",~"GDP per capita PPP$",~"GII 2020 rank",
"United Kingdom",4,6,7,"High","EUR",67.9,2978.6,44288,4,
) 

df1 %>% 
  select(1:2) %>%
  gt() %>%
  cols_label(ADMIN="") %>%
  tab_style(
    style = list(cell_text(font=google_font("Roboto"), weight="bold")),
    locations = cells_body()) %>%
  tab_style(
    style = list(cell_text(font=google_font("Roboto"))),
    locations = cells_column_labels())

df1 %>% 
  select(3:10) %>%
  gt() %>%
  tab_style(
    style = list(cell_text(font=google_font("Roboto"))),
    locations = cells_body()) %>%
  cols_align(align="center") %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels()) 
```

### 2021 Ranking Overview

```{r}
df2 = tribble(
  ~ADMIN,~Year,~Category,~"Sub Category",~Score,~Rank,~Group,
  "United Kingdom",2020,"INSTITUTIONS","1 INSTITUTIONS",86.1,16,1,
  "United Kingdom",2020,"INSTITUTIONS","1.1 Political environment",78.8,25,0,
  "United Kingdom",2020,"INSTITUTIONS","1.2 Regulatory environment",93.1,8,0,
  "United Kingdom",2020,"INSTITUTIONS","1.3 Business environment",87.4,12,0,
  "United Kingdom",2020,"HUMAN CAPITAL & RESEARCH","2 HUMAN CAPITAL & RESEARCH",58.0,10,1,
  "United Kingdom",2020,"HUMAN CAPITAL & RESEARCH","2.1 Education",55.2,35,0,
  "United Kingdom",2020,"HUMAN CAPITAL & RESEARCH","2.2 Tertiary education",51.3,15,0,
  "United Kingdom",2020,"HUMAN CAPITAL & RESEARCH","2.3 Research and development (R&D)",67.6,9,0,
  "United Kingdom",2020,"INFRASTRUCTURE","3 INFRASTRUCTURE",60.3,6,1,
  "United Kingdom",2020,"INFRASTRUCTURE","3.1 ICTs",93.6,1,0,
  "United Kingdom",2020,"INFRASTRUCTURE","3.2 General infrastructure",33.1,38,0,
  "United Kingdom",2020,"INFRASTRUCTURE","3.3 Ecological sustainability",54.2,14,0,
  "United Kingdom",2020,"MARKET SOPHISTICATION","4 MARKET SOPHISTICATION",74.4,5,1,
  "United Kingdom",2020,"MARKET SOPHISTICATION","4.1 Credit",68.1,8,0,
  "United Kingdom",2020,"MARKET SOPHISTICATION","4.2 Investment",73.9,5,0,
  "United Kingdom",2020,"MARKET SOPHISTICATION","4.3 Trade, diversification, and market scale",91.3,4,0,
  "United Kingdom",2020,"BUSINESS SOPHISTICATION","5 BUSINESS SOPHISTICATION",51.0,19,1,
  "United Kingdom",2020,"BUSINESS SOPHISTICATION","5.1 Knowledge workers",59.6,16,0,
  "United Kingdom",2020,"BUSINESS SOPHISTICATION","5.2 Innovation linkages",51.0,14,0,
  "United Kingdom",2020,"BUSINESS SOPHISTICATION","5.3 Knowledge absorption",42.5,27,0,
  "United Kingdom",2020,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6 KNOWLEDGE & TECHNOLOGY OUTPUTS",54.4,9,1,
  "United Kingdom",2020,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.1 Knowledge creation",66.2,6,0,
  "United Kingdom",2020,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.2 Knowledge impact",45.3,10,0,
  "United Kingdom",2020,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.3 Knowledge diffusion",51.8,11,0,
  "United Kingdom",2020,"CREATIVE OUTPUTS","7 CREATIVE OUTPUTS",52.7,5,1,
  "United Kingdom",2020,"CREATIVE OUTPUTS","7.1 Intangible assets",53.9,9,0,
  "United Kingdom",2020,"CREATIVE OUTPUTS","7.2 Creative goods and services",41.6,10,0,
  "United Kingdom",2020,"CREATIVE OUTPUTS","7.3 Online creativity",61.6,10,0,
  "United Kingdom",2021,"INSTITUTIONS","1 INSTITUTIONS",86.6,15,1,
  "United Kingdom",2021,"INSTITUTIONS","1.1 Political environment",80.0,21,0,
  "United Kingdom",2021,"INSTITUTIONS","1.2 Regulatory environment",92.4,9,0,
  "United Kingdom",2021,"INSTITUTIONS","1.3 Business environment",87.4,12,0, 
  "United Kingdom",2021,"HUMAN CAPITAL & RESEARCH","2 HUMAN CAPITAL & RESEARCH",58.2,10,1,
  "United Kingdom",2021,"HUMAN CAPITAL & RESEARCH","2.1 Education",59.7,28,0,
  "United Kingdom",2021,"HUMAN CAPITAL & RESEARCH","2.2 Tertiary education",47.4,18,0,
  "United Kingdom",2021,"HUMAN CAPITAL & RESEARCH","2.3 Research and development (R&D)",67.7,9,0,
  "United Kingdom",2021,"INFRASTRUCTURE","3 INFRASTRUCTURE",59.7,10,1,
  "United Kingdom",2021,"INFRASTRUCTURE","3.1 ICTs",93.4,2,0,
  "United Kingdom",2021,"INFRASTRUCTURE","3.2 General infrastructure",34.7,40,0,
  "United Kingdom",2021,"INFRASTRUCTURE","3.3 Ecological sustainability",50.9,14,0,
  "United Kingdom",2021,"MARKET SOPHISTICATION","4 MARKET SOPHISTICATION",78.1,4,1,
  "United Kingdom",2021,"MARKET SOPHISTICATION","4.1 Credit",65.3,10,0,
  "United Kingdom",2021,"MARKET SOPHISTICATION","4.2 Investment",80.0,5,0,
  "United Kingdom",2021,"MARKET SOPHISTICATION","4.3 Trade, diversification, and market scale",89.1,3,0,
  "United Kingdom",2021,"BUSINESS SOPHISTICATION","5 BUSINESS SOPHISTICATION",49.7,21,1,
  "United Kingdom",2021,"BUSINESS SOPHISTICATION","5.1 Knowledge workers",61.2,14,0,
  "United Kingdom",2021,"BUSINESS SOPHISTICATION","5.2 Innovation linkages",47.0,17,0,
  "United Kingdom",2021,"BUSINESS SOPHISTICATION","5.3 Knowledge absorption",40.7,27,0,
  "United Kingdom",2021,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6 KNOWLEDGE & TECHNOLOGY OUTPUTS",52.3,10,1,
  "United Kingdom",2021,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.1 Knowledge creation",65.0,8,0,
  "United Kingdom",2021,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.2 Knowledge impact",43.1,19,0,
  "United Kingdom",2021,"KNOWLEDGE & TECHNOLOGY OUTPUTS","6.3 Knowledge diffusion",48.9,15,0,
  "United Kingdom",2021,"CREATIVE OUTPUTS","7 CREATIVE OUTPUTS",54.0,4,1,
  "United Kingdom",2021,"CREATIVE OUTPUTS","7.1 Intangible assets",56.0,10,0,
  "United Kingdom",2021,"CREATIVE OUTPUTS","7.2 Creative goods and services",44.8,6,0,
  "United Kingdom",2021,"CREATIVE OUTPUTS","7.3 Online creativity",59.0,10,0
) %>%
  mutate(Section= case_when(Category=="INSTITUTIONS"~1,
                            Category=="HUMAN CAPITAL & RESEARCH"~1,
                            Category=="INFRASTRUCTURE"~1,
                            Category=="MARKET SOPHISTICATION"~1,
                            Category=="BUSINESS SOPHISTICATION"~2,
                            Category=="KNOWLEDGE & TECHNOLOGY OUTPUTS"~2,
                            Category=="CREATIVE OUTPUTS"~2)) %>%
  mutate("Sub Category"= case_when(Group==1 ~ paste0("<b>",`Sub Category`,"</b>"),
                                   Group==0 ~ paste0(`Sub Category`))) %>%
  mutate(`Sub Category`= fct_rev(fct_inorder(`Sub Category`)),
         Category= fct_inorder(Category),
         )
```

    
```{r}
df2a = df2 %>% select(ADMIN, Year, Category,`Sub Category`,Rank,Group,Section) %>%
  pivot_wider(names_from=Year, values_from=Rank) %>%
  #filter(Section==1) %>%
  mutate(change= case_when(`2020`==`2021`~"No change",
                           `2021`>`2020`~"Down",
                           `2021`<`2020`~"Up")) 
```

```{r, fig.height=4, fig.width=4}
df2a %>%
  ggplot(aes(y=`Sub Category`, x=`2021`, 
             shape=fct_rev(change),fill=fct_rev(change))) +
  geom_segment(aes(xend=`2021`, x=`2020`, y=`Sub Category`,yend=`Sub Category`), 
               size=1, alpha=.5) +
  geom_point(size=3.3) +
  scale_x_continuous(breaks=seq(min(df2a$`2021`),max(df2a$`2021`),10), sec.axis = dup_axis()) +
  scale_shape_manual("Rank change from 2020",values=c(24,22,25)) +
  scale_fill_manual("Rank change from 2020",values=c("#219ebc","#e5e5e5","#fb8500")) +
  theme_minimal(base_size = 12.2, base_family = "Roboto") +
  theme(legend.position="top",
        axis.text.y=element_markdown(color="black"),
        panel.grid=element_line(size=.3),
        plot.margin=margin(.5,1,.5,.5,unit="cm"),
        legend.title = element_text(size=10),
        axis.text.x=element_text(color="black"),
        axis.title.x.bottom = element_blank(),
        axis.title.x.top = element_text(size=10.5, margin=margin(b=4), family="Libre Franklin", 
                                        face="bold"),
        legend.margin=margin(l=-16, unit="cm"),
        plot.title.position = "plot",
        plot.title=element_text(family="Libre Franklin", hjust=0, face="bold")
        ) +
  labs(y=NULL, x="2021 Rank",title=country)
```

### Creative Outputs
```{r}
# expanded
df3 = 
tribble(
  ~ADMIN,~Categoryid,~Category,~Score,~Rank,~Level,
  "United Kingdom","7","CREATIVE OUTPUTS",54.0,4,1,
  "United Kingdom","7.1","Intangible assets",56.0,10,2,
  "United Kingdom","7.1.1","Trademarks by origin/bn PPP$ GDP",53.8,40,3,
  "United Kingdom","7.1.2","Global brand value, top 5,000, % GDP",160.7,8,3,
  "United Kingdom","7.1.3","Industrial designs by origin/bn PPP$ GDP",8.5,14,3,
  "United Kingdom","7.1.4","ICTs and organizational model creation",79.1,6,3,
  "United Kingdom","7.2","Creative goods and services",44.8,6,2,
  "United Kingdom","7.2.1","Cultural and creative services exports, % total trade",2.5,6,3,
  "United Kingdom","7.2.2","National feature films/mn pop. 15–69",6.2,36,3,
  "United Kingdom","7.2.3"," Entertainment and media market/th pop. 15–69",61.8,8,3,
  "United Kingdom","7.2.4","Printing and other media, % manufacturing",1.9,18,3,
  "United Kingdom","7.2.5","Creative goods exports, % total trade",3.5,16,3,
  "United Kingdom","7.3","Online creativity",59.0,10,2,
  "United Kingdom","7.3.1","Generic top-level domains (TLDs)/th pop. 15–69",60.1,10,3,
  "United Kingdom","7.3.2","Country-code TLDs/th pop. 15–69",69.4,8,3,
  "United Kingdom","7.3.3","Wikipedia edits/mn pop. 15–69",80.0,11,3,
  "United Kingdom","7.3.4","Mobile app creation/bn PPP$ GDP",22.4,24,3
) 
```


```{r}
df3 %>% select(-ADMIN) %>%
  gt() %>%
  cols_label(Categoryid="",
             Category="") %>%
  tab_style(
    style = list(cell_text(weight = "bold")),
    locations = cells_body(rows = Level<3))  %>%
  tab_style(
    style = list(cell_text(font=google_font("Roboto"))),
    locations = cells_body()) %>%
  cols_hide(Level) %>%
  tab_options(table.font.size = px(13)) %>%
  gt_color_rows(Rank,domain=1:132, palette="ggsci::indigo_material")
```